server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG
oauth2:
  client-id: relive-client
  client-secret: relive-client-secret
  token-uri: http://localhost:8080/oauth2/token
  redirect-uri: http://127.0.0.1:8070/login/oauth2/code/relive-client
spring:
  main:
    allow-bean-definition-overriding: true
